### ISSUE TITLE
Varying layer infill shift per layer

### ISSUE THREAD

**Issue by alex43543** [VanHulleOne/SciSlice#6]
Hi there,
i was trying to use the layer shifting option in your Slicer, but couldt get it working properly.
My main goal was to shift half of the infill layers sligthly, so that the new lines sit in the Valley of the old ones. 
We seperated the two Layer Parameter with a comma, but it didn´t work. All other Layer-Parameters worked in this way.

Thank you for your help

**Comment by VanHulleOne** [comment]
Before I dig too much into this I want to ensure that you using `Infill Shift X` and `Infill Shift Y` as opposed to `Shift X` and `Shift Y`. The former shifts individual layers and the later shifts the whole part.

**Comment by alex43543** [comment]
Hello,
I just tried it again. This time it worked directly, strangely enough. But I used exactly the same settings....
Sorry for the troubles

**Comment by VanHulleOne** [comment]
No worries. I'm glad it worked. Hopefully no more mysteries!
